export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'

export const FETCHING_REQUEST_TOKEN = 'FETCHING_REQUEST_TOKEN'

export const FETCHING_SESSION = 'FETCHING_SESSION'
export const FETCHING_SESSION_SUCCESS = 'FETCHING_SESSION_SUCCESS'
export const FETCHING_SESSION_ERROR = 'FETCHING_SESSION_ERROR'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
